export const MOVIE_GENRES = {
  28: 'Action',
  12: 'Adventure',
  16: 'Animation',
  35: 'Comedy',
  80: 'Crime',
  99: 'Documentary',
  18: 'Drama',
  10751: 'Family',
  14: 'Fantasy',
  36: 'History',
  27: 'Horror',
  10402: 'Music',
  9648: 'Mystery',
  10749: 'Romance',
  878: 'Science Fiction',
  10770: 'TV Movie',
  53: 'Thriller',
  10752: 'War',
  37: 'Western',
};

export const TV_GENRES = {
  10759: 'Action & Adventure',
  16: 'Animation',
  35: 'Comedy',
  80: 'Crime',
  99: 'Documentary',
  18: 'Drama',
  10751: 'Family',
  10762: 'Kids',
  9648: 'Mystery',
  10763: 'News',
  10764: 'Reality',
  10765: 'Sci-Fi & Fantasy',
  10766: 'Soap',
  10767: 'Talk',
  10768: 'War & Politics',
  37: 'Western',
};

export const MOVIE_CERTIFICATION = {
  // US
  0: 'NR',
  1: 'G',
  2: 'PG',
  3: 'PG-13',
  4: 'R',
  5: 'NC-17',
};

export const TV_CERTIFICATION = {
  // US
  0: 'NR',
  1: 'TV-Y',
  2: 'TV-Y7',
  3: 'TV-G',
  4: 'TV-PG',
  5: 'TV-14',
  6: 'TV-MA',
};

export const RELEASE_DATE_TYPES = {
  1: 'Premiere',
  2: 'Theatrical (limited)',
  3: 'Theatrical',
  4: 'Digital',
  5: 'Physical',
  6: 'TV',
};

export const LANGUAGES = {
  bi: 'Bislama',
  cs: 'Czech',
  ba: 'Bashkir',
  ae: 'Avestan',
  av: 'Avaric',
  de: 'German',
  mt: 'Maltese',
  om: 'Oromo',
  rm: 'Raeto-Romance',
  so: 'Somali',
  ts: 'Tsonga',
  vi: 'Vietnamese',
  gn: 'Guarani',
  ig: 'Igbo',
  it: 'Italian',
  ki: 'Kikuyu',
  ku: 'Kurdish',
  la: 'Latin',
  ln: 'Lingala',
  lb: 'Letzeburgesch',
  ny: 'Chichewa; Nyanja',
  pl: 'Polish',
  si: 'Sinhalese',
  to: 'Tonga',
  az: 'Azerbaijani',
  ce: 'Chechen',
  cu: 'Slavic',
  da: 'Danish',
  hz: 'Herero',
  ie: 'Interlingue',
  rw: 'Kinyarwanda',
  mi: 'Maori',
  no: 'Norwegian',
  pi: 'Pali',
  sk: 'Slovak',
  se: 'Northern Sami',
  sm: 'Samoan',
  uk: 'Ukrainian',
  en: 'English',
  ay: 'Aymara',
  ca: 'Catalan',
  eo: 'Esperanto',
  ha: 'Hausa',
  ho: 'Hiri Motu',
  hu: 'Hungarian',
  io: 'Ido',
  ii: 'Yi',
  kn: 'Kannada',
  kv: 'Komi',
  li: 'Limburgish',
  oj: 'Ojibwa',
  ru: 'Russian',
  sr: 'Serbian',
  sv: 'Swedish',
  ty: 'Tahitian',
  zu: 'Zulu',
  ka: 'Georgian',
  ch: 'Chamorro',
  be: 'Belarusian',
  br: 'Breton',
  kw: 'Cornish',
  fi: 'Finnish',
  sh: 'Serbo-Croatian',
  nn: 'Norwegian Nynorsk',
  tt: 'Tatar',
  tg: 'Tajik',
  vo: 'Volapük',
  ps: 'Pushto',
  mk: 'Macedonian',
  fr: 'French',
  bm: 'Bambara',
  eu: 'Basque',
  fj: ':Fijian',

  id: 'Indonesian',

  mg: 'Malagasy',
  na: 'Nauru',
  xx: 'No Language',
  qu: 'Quechua',
  sq: 'Albanian',
  ti: 'Tigrinya',
  tw: 'Twi',
  wa: 'Walloon',
  ab: 'Abkhazian',
  bs: 'Bosnian',
  af: 'Afrikaans',
  an: 'Aragonese',
  fy: 'Frisian',
  gu: 'Gujarati',
  ik: 'Inupiaq',
  ja: 'Japanese',
  ko: 'Korean',
  lg: 'Ganda',
  nl: 'Dutch',
  os: 'Ossetian',
  el: 'Greek',
  bn: 'Bengali',
  cr: 'Cree',
  km: 'Khmer',
  lo: 'Lao',
  nd: 'Ndebele',
  ne: 'Nepali',
  sc: 'Sardinian',
  sw: 'Swahili',
  tl: 'Tagalog',
  ur: 'Urdu',
  ee: 'Ewe',
  aa: 'Afar',
  co: 'Corsican',
  et: 'Estonian',
  is: 'Icelandic',
  ks: 'Kashmiri',
  kr: 'Kanuri',
  ky: 'Kirghiz',
  kj: 'Kuanyama',
  nr: 'Ndebele',
  or: 'Oriya',
  wo: 'Wolof',
  za: 'Zhuang',
  ar: 'Arabic',
  cv: 'Chuvash',
  fo: 'Faroese',
  hr: 'Croatian',
  ms: 'Malay',
  nb: 'Norwegian Bokmål',
  rn: 'Rundi',
  sn: 'Shona',
  st: 'Sotho',
  tr: 'Turkish',
  am: 'Amharic',
  fa: 'Persian',
  hy: 'Armenian',
  pa: 'Punjabi',
  as: 'Assamese',
  ia: 'Interlingua',
  lv: 'Latvian',
  lu: 'Luba-Katanga',
  mr: 'Marathi',
  mn: 'Mongolian',
  pt: 'Portuguese',
  th: 'Thai',
  tk: 'Turkmen',
  ve: 'Venda',
  dv: 'Divehi',
  gv: 'Manx',
  kl: 'Kalaallisut',
  kk: 'Kazakh',
  lt: 'Lithuanian',
  my: 'Burmese',
  sl: 'Slovenian',
  sd: 'Sindhi',
  cn: 'Cantonese',
  hi: 'Hindi',
  cy: 'Welsh',
  ht: 'Haitian',
  iu: 'Inuktitut',
  jv: 'Javanese',
  mh: 'Marshall',
  sa: 'Sanskrit',
  ss: 'Swati',
  te: 'Telugu',
  kg: 'Kongo',
  ml: 'Malayalam',
  uz: 'Uzbek',
  sg: 'Sango',
  xh: 'Xhosa',
  es: 'Spanish',
  su: 'Sundanese',
  ug: 'Uighur',
  yi: 'Yiddish',
  yo: 'Yoruba',
  zh: 'Mandarin',
  he: 'Hebrew',
  bo: 'Tibetan',
  ak: 'Akan',
  mo: 'Moldavian',
  ng: 'Ndonga',
  dz: 'Dzongkha',
  ff: 'Fulah',
  gd: 'Gaelic',
  ga: 'Irish',
  gl: 'Galician',
  nv: 'Navajo',
  oc: 'Occitan',
  ro: 'Romanian',
  ta: 'Tamil',
  tn: 'Tswana',
  bg: 'Bulgarian',
};
